### PR TITLE
euicc: added support for multiple AIDs

### LINKED ISSUE #157: 'SCardTransmit() failed: 0000045D' on 5ber Ultra eUICC chip
```console
> C:\Users\Joey Oropesa\.minilpa\windows_x86\Dir\lpac.exe version
{"type":"lpa","payload":{"code":0,"message":"success","data":"v2.1.0"}}
> C:\Users\Joey Oropesa\.minilpa\windows_x86\Dir\lpac.exe driver apdu list
{"type":"driver","payload":{"env":"DRIVER_IFID","data":[{"env":"0","name":"Generic Smart Card Reader Interface 0"}]}}
> C:\Users\Joey Oropesa\.minilpa\windows_x86\Dir\lpac.exe profile list
{"type":"lpa","payload":{"code":-1,"message":"euicc_init","data":""}}
SCardTransmit() failed: 0000045D
SCardTransmit() failed: 0000045D
```
It simply doesn't read the card at all.

### LINKED ISSUE #175: euicc_init failed on 5ber standard edition
I'm trying to use EasyLPAC (windows 11) with a 5ber "standard" eSim card.
I am using this card reader http://www.aliexpress.com/item/1005006885571475.html

I get a popup
Lpac error
Function:euicc_init
Data:
Please check log for details

When I look at the log:
C:\temp\EasyLPAC-windows-x86_64-with-lpac\lpac.exe version
{"type":"lpa","payload":{"code":0,"message":"success","data":"v2.1.0"}}

C:\temp\EasyLPAC-windows-x86_64-with-lpac\lpac.exe driver apdu list
{"type":"driver","payload":{"env":"DRIVER_IFID","data":[{"env":"0","name":"Generic Smart Card Reader Interface 0"}]}}
C:\temp\EasyLPAC-windows-x86_64-with-lpac\lpac.exe profile list
{"type":"lpa","payload":{"code":-1,"message":"euicc_init","data":""}}

I messaged EasyLPAC and was told it is an LPAC issue.

What am I doing wrong??

Thanks.

### PR DESCRIPTION
**Pull request by Root-Core**
euicc: added support for multiple AIDs
- Added env variable "LPAC_CUSTOM_ISD_R_AID" for user defined AIDs
- Added documentation for new env var

Closes #157
Closes #175

Not tested for #157, feedback appreciated.

### CODE REVIEW

**Comment by septs** [comment]
> 5ber products are safe and trustworthy, strictly complying with GSMA technical standards

from <https://esim.5ber.com/bulletin?language=en-US>

**Review by septs — CHANGES_REQUESTED** [review]
> 5ber products are safe and trustworthy, strictly complying with GSMA technical standards

from <https://esim.5ber.com/bulletin?language=en-US>

**Comment by estkme** [comment]
As https://github.com/estkme-group/lpac/issues/157#issuecomment-2488237116 said, we can't accept a very certain byte sequence (since that AID isn't a public information) merged in to our code base, so we will happy to accept the env part, would you like to adjust your pr? Thanks.

**Comment by septs** [comment]
plz move the logical to `src/main.c`, setting `aid` in `euicc_ctx`

https://github.com/estkme-group/lpac/blob/62eb766d14f0818e6bbed96a1e6e35106a24af76/src/main.c#L57-L67

**Comment by Root-Core** [comment]
@estkme Sure, that would be fine in my jurisdiction. I changed it accordingly.

@septs Done, I hope this implementation looks okay to you. And yeah... 5ber is not really following the standards here. A bit ironic.

File: src/main.c [hunk 1]
```diff
@@ -58,6 +61,21 @@ struct euicc_ctx euicc_ctx = {0};
...
+    const char *custom_aid_str = getenv("LPAC_CUSTOM_ISD_R_AID");
+    if (custom_aid_str)
+    {
+        unsigned char custom_aid[ISD_R_AID_STR_LENGTH];
+        const int custom_aid_len = euicc_hexutil_hex2bin(custom_aid, ISD_R_AID_STR_LENGTH, custom_aid_str);
+        if (custom_aid_len != ISD_R_AID_STR_LENGTH)
+        {
+            jprint_error("euicc_init", "invalid custom AID given");
+            exit(-1);
+        }
```
Comment (CoelacanthusHex) [inline src/main.c:73]: If the user gives a hex string larger than 16B, it will be truncated silently. This is not a good practice. Please check the length before passing the hex string into `euicc_hexutil_hex2bin()`.

Comment (Root-Core) [reply src/main.c:73]: Isn't this actually checked in `euicc_hexutil_hex2bin` already?

Comment (CoelacanthusHex) [reply src/main.c:73]: Sorry, I read the wrong line.

**Review by septs — APPROVED** [review]
wait for @estkme approve

**Comment by tcmaps** [comment]
Advocating for a tack `ISDR_AID` :)
